### ISSUE TITLE
provision all brings down wlan0

### ISSUE THREAD

**Issue by arjunmenon** [radiodan/provision#14]
`sudo ./provision iptables node wifi-connect`
After running this, it did something to the iptables but couldn't download node or wifi-connect.

Problem was after this my Pi3 does not connect to wifi anymore.
After that point doing ifconfig wlan0 prompted wlan0 does not exist.
So I decided to reflash the SD card but the problem has persisted.

Before the iptables thing, when running `sudo wpa_supplicant -Dn180211 -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf` earlier it showed something about the driver.

But after that iptables thing, running that command simply said the driver was unsupported and this persisted even after reflashing the SD card.

Can you help me out, please?

**Comment by libbymiller** [comment]
Sorry, I've not come across this and don't see how it can persist after reflashing unless it's the command you're using (where did you get the command `sudo wpa_supplicant -Dn180211 -iwlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf` from? Looks like `nl80211` is the driver name - you seem to have `n180211` (i.e. a 1 instead of an l for the second character of the driver name).

**Comment by arjunmenon** [comment]
Hey
Somehow it works now.
I correctly dont know what the issue is, but an additional change I made to the `wpa_supplicant.conf` file was adding `key_mgmt=WPA-PSK`.
I never had to do it before and neither I had to add this in another SD card I have of a different project. But yeah, it worked.

One more note, when I tired to configure this manually as guided from that blog,

```
mkdir -pv /opt/node && \
  $(curl -L https://nodejs.org/dist/v5.10.0/node-v5.10.0-linux-armv6l.tar.gz | tar xz --strip-components 1 -C /opt/node) && \
  ln -sf /opt/node/bin/node /usr/local/bin/node && \
  ln -sf /opt/node/bin/npm /usr/local/bin/npm && \
  /opt/node/bin/npm config set prefix /usr/local
```

This step does not work.
It outputs that the
`gzip: stdin is not in gzip format`

And, if I would simply do `sudo ./provision node`, that one outputs
`no config step for node`

But the setup works for `sudo ./provision iptables node wifi-connect`

**Comment by andrewn** [comment]
> And, if I would simply do sudo ./provision node, that one outputs
> no config step for node

That's because provisioning is a two step process. Each thing that is installed potentially has two steps, `install` and `config`. In the case of `node`, it only has an `install` step. So, it probably did install node but this message is a bit confusing.
