### ISSUE TITLE
nginx installation fails on provision

### ISSUE THREAD

**Issue by libbymiller** [radiodan/provision#3]
steps:
git clone https://github.com/radiodan/provision.git
cd provision
git fetch origin
git checkout -b broker origin/broker
sudo LOG_LEVEL=DEBUG ./provision nginx

nginx: Setting up nginx-full (1.9.2-1) ...
nginx: Starting nginx: nginx failed!
nginx: invoke-rc.d: initscript nginx, action "start" failed.
nginx: dpkg: error processing nginx-full (--configure):
nginx:  subprocess installed post-installation script returned error exit status 1
nginx: dpkg: dependency problems prevent configuration of nginx:
nginx: nginx depends on nginx-full (>= 1.9.2-1) | nginx-light (>= 1.9.2-1) | nginx-extras (>=
1.9.2-1); however:
nginx:   Package nginx-full is not configured yet.
nginx:   Package nginx-light is not installed.
nginx:   Package nginx-extras is not installed.
nginx: nginx depends on nginx-full (<< 1.9.2-1.1~) | nginx-light (<< 1.9.2-1.1~) | nginx-extras
(<< 1.9.2-1.1~); however:
nginx:   Package nginx-full is not configured yet.
nginx:   Package nginx-light is not installed.
nginx:   Package nginx-extras is not installed.
nginx:
nginx: dpkg: error processing nginx (--configure):
nginx:  dependency problems - leaving unconfigured
nginx: Errors were encountered while processing:
nginx:  nginx-full
nginx:  nginx
nginx: E: Sub-process /usr/bin/dpkg returned an error code (1)
Failed nginx install.
Skipped nginx config, due to presence in failed steps
1 steps selected, 1 failed.
Failed steps: nginx

solution is to remove line in
        listen [::]:80 default_server;

in /etc/nginx/sites-enabled/default

**Comment by andrewn** [comment]
Now that we use `iptables` to map port 80 to port 5000 we allow the app running on port 5000 to provide it's own HTTP server.
