### ISSUE TITLE
Magic button from provision has no player in config file

### ISSUE THREAD

**Issue by libbymiller** [radiodan/provision#5]
/opt/radiodan/apps/magic-button/current/config/radiodan-config.json

has no 

```
 "player" 
```

in default.

Not sure if this is a magic button problem or a provision problem.

**Comment by tthef** [comment]
It defaults to mpd when nothing is set. I am patching the config file in the Yocto build to set this to mopidy, since the Yocto images do not include mpd at all.

**Comment by andrewn** [comment]
Closing as we now don't bundle the magic-button player with this repo.
